-- Bundled Lua generated by Lmaobox Context Server
-- Entry point: Main.lua

local __bundle_modules = {}
local __bundle_loaded = {}

local function __bundle_require(name)
    local loader = __bundle_modules[name]
    if loader == nil then
        return require(name)
    end

    local cached = __bundle_loaded[name]
    if cached ~= nil then
        return cached
    end

    local loaded = loader()
    if loaded == nil then
        loaded = true
    end

    __bundle_loaded[name] = loaded
    return loaded
end

-- Module: math_helpers
__bundle_modules["math_helpers"] = function()
-- Simple math helpers
local math_helpers = {}

function math_helpers.add(a, b)
    return a + b
end

return math_helpers


end

-- Entry point
-- Simple example with dependency
local math_helpers = __bundle_require("math_helpers")

print("Testing bundle with dependency...")
local result = math_helpers.add(2, 2)
print("2 + 2 = " .. result)

local M = {}

function M.run()
    print("Main.run() executed")
end

return M
